-- Cria generator se não existir
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$GENERATORS g 
     WHERE UPPER(g.RDB$GENERATOR_NAME) = 'GEN_CONVERSAS_ID'
  )) THEN
  BEGIN
    EXECUTE STATEMENT 'CREATE GENERATOR GEN_CONVERSAS_ID';
  END
END;

-- Opcional: sincroniza generator com o maior ID atual
EXECUTE BLOCK AS
  DECLARE VARIABLE MAXID Int;
BEGIN
  SELECT COALESCE(MAX(ID), 0) FROM CONVERSAS INTO :MAXID;
  EXECUTE STATEMENT 'SET GENERATOR GEN_CONVERSAS_ID TO ' || :MAXID;
END;

-- Cria trigger BEFORE INSERT para preencher ID se vier NULL
EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS t 
     WHERE UPPER(t.RDB$TRIGGER_NAME) = 'BI_CONVERSAS_ID' 
       AND t.RDB$RELATION_NAME = 'CONVERSAS'
  )) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TRIGGER BI_CONVERSAS_ID FOR CONVERSAS
      ACTIVE BEFORE INSERT POSITION 0
      AS
      BEGIN
        IF (NEW.ID IS NULL) THEN
          NEW.ID = GEN_ID(GEN_CONVERSAS_ID, 1);
      END
    ';
  END
END;
