/* 1) Triggers de auto-incremento (idempotentes) */
CREATE OR ALTER TRIGGER BI_MENUS FOR MENUS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MENUS_ID, 1);
END;

CREATE OR ALTER TRIGGER BI_MENU_OPCOES FOR MENU_OPCOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MENU_OPCOES_ID, 1);
END;

/* Se a tabela CONVERSAS existir, deixe este bloco.
   Se NÃO existir na sua base, comente as 6 linhas abaixo. */
CREATE OR ALTER TRIGGER BI_CONVERSAS FOR CONVERSAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CONVERSAS_ID, 1);
END;

/* 2) Sincroniza generators ao topo das tabelas (FB 2.5) */

/* MENUS */
EXECUTE BLOCK AS
  DECLARE VARIABLE v    INT;
  DECLARE VARIABLE cur  INT;
  DECLARE VARIABLE delta INT;
BEGIN
  SELECT COALESCE(MAX(ID), 0) FROM MENUS INTO :v;
  SELECT GEN_ID(GEN_MENUS_ID, 0) FROM RDB$DATABASE INTO :cur;
  delta = v - cur;

  IF (delta > 0) THEN
    SELECT GEN_ID(GEN_MENUS_ID, :delta) FROM RDB$DATABASE INTO :cur;
  ELSE
  BEGIN
    IF (delta < 0) THEN
      EXECUTE STATEMENT 'SET GENERATOR GEN_MENUS_ID TO ' || :v;
  END
END;

/* MENU_OPCOES */
EXECUTE BLOCK AS
  DECLARE VARIABLE v    INT;
  DECLARE VARIABLE cur  INT;
  DECLARE VARIABLE delta INT;
BEGIN
  SELECT COALESCE(MAX(ID), 0) FROM MENU_OPCOES INTO :v;
  SELECT GEN_ID(GEN_MENU_OPCOES_ID, 0) FROM RDB$DATABASE INTO :cur;
  delta = v - cur;

  IF (delta > 0) THEN
    SELECT GEN_ID(GEN_MENU_OPCOES_ID, :delta) FROM RDB$DATABASE INTO :cur;
  ELSE
  BEGIN
    IF (delta < 0) THEN
      EXECUTE STATEMENT 'SET GENERATOR GEN_MENU_OPCOES_ID TO ' || :v;
  END
END;

/* CONVERSAS (execute só se a tabela existir) */
EXECUTE BLOCK AS
  DECLARE VARIABLE exists_tbl SMALLINT;
  DECLARE VARIABLE v    INT;
  DECLARE VARIABLE cur  INT;
  DECLARE VARIABLE delta INT;
BEGIN
  SELECT COUNT(*)
    FROM RDB$RELATIONS
   WHERE RDB$SYSTEM_FLAG = 0
     AND TRIM(UPPER(RDB$RELATION_NAME)) = 'CONVERSAS'
   INTO :exists_tbl;

  IF (exists_tbl > 0) THEN
  BEGIN
    SELECT COALESCE(MAX(ID), 0) FROM CONVERSAS INTO :v;
    SELECT GEN_ID(GEN_CONVERSAS_ID, 0) FROM RDB$DATABASE INTO :cur;
    delta = v - cur;

    IF (delta > 0) THEN
      SELECT GEN_ID(GEN_CONVERSAS_ID, :delta) FROM RDB$DATABASE INTO :cur;
    ELSE
    BEGIN
      IF (delta < 0) THEN
        EXECUTE STATEMENT 'SET GENERATOR GEN_CONVERSAS_ID TO ' || :v;
    END
  END
END;

/* 3) Dados do menu */
MERGE INTO MENUS m
USING (SELECT 1 AS CLIENTE_ID FROM RDB$DATABASE) src
ON (m.CLIENTE_ID = src.CLIENTE_ID AND m.ATIVO = 1)
WHEN NOT MATCHED THEN
  INSERT (CLIENTE_ID, TITULO, ATIVO) VALUES (1, 'Menu principal', 1);

/* Opções do menu (CHAVE_PAI='root') */
MERGE INTO MENU_OPCOES mo
USING (SELECT (SELECT ID FROM MENUS WHERE CLIENTE_ID=1 AND ATIVO=1) AS MENU_ID FROM RDB$DATABASE) src
ON (mo.MENU_ID = src.MENU_ID AND mo.CHAVE_PAI='root' AND mo.OPCAO='1')
WHEN NOT MATCHED THEN
  INSERT (MENU_ID, CHAVE_PAI, OPCAO, TEXTO, PROXIMA_CHAVE, ORDEM)
  VALUES (src.MENU_ID, 'root', '1', 'Detalhes da entrega', 'ASK_NOMOVTRA', 1);

MERGE INTO MENU_OPCOES mo
USING (SELECT (SELECT ID FROM MENUS WHERE CLIENTE_ID=1 AND ATIVO=1) AS MENU_ID FROM RDB$DATABASE) src
ON (mo.MENU_ID = src.MENU_ID AND mo.CHAVE_PAI='root' AND mo.OPCAO='2')
WHEN NOT MATCHED THEN
  INSERT (MENU_ID, CHAVE_PAI, OPCAO, TEXTO, PROXIMA_CHAVE, ORDEM)
  VALUES (src.MENU_ID, 'root', '2', 'Registrar ocorrência', 'ASK_OCORRENCIA_TEXTO', 2);

MERGE INTO MENU_OPCOES mo
USING (SELECT (SELECT ID FROM MENUS WHERE CLIENTE_ID=1 AND ATIVO=1) AS MENU_ID FROM RDB$DATABASE) src
ON (mo.MENU_ID = src.MENU_ID AND mo.CHAVE_PAI='root' AND mo.OPCAO='3')
WHEN NOT MATCHED THEN
  INSERT (MENU_ID, CHAVE_PAI, OPCAO, TEXTO, PROXIMA_CHAVE, ORDEM)
  VALUES (src.MENU_ID, 'root', '3', 'Enviar CT-e', 'ASK_CTE_ARQUIVO_OU_CHAVE', 3);

MERGE INTO MENU_OPCOES mo
USING (SELECT (SELECT ID FROM MENUS WHERE CLIENTE_ID=1 AND ATIVO=1) AS MENU_ID FROM RDB$DATABASE) src
ON (mo.MENU_ID = src.MENU_ID AND mo.CHAVE_PAI='root' AND mo.OPCAO='4')
WHEN NOT MATCHED THEN
  INSERT (MENU_ID, CHAVE_PAI, OPCAO, TEXTO, PROXIMA_CHAVE, ORDEM)
  VALUES (src.MENU_ID, 'root', '4', 'Enviar doc. motorista', 'ASK_DOC_MOTORISTA', 4);

MERGE INTO MENU_OPCOES mo
USING (SELECT (SELECT ID FROM MENUS WHERE CLIENTE_ID=1 AND ATIVO=1) AS MENU_ID FROM RDB$DATABASE) src
ON (mo.MENU_ID = src.MENU_ID AND mo.CHAVE_PAI='root' AND mo.OPCAO='5')
WHEN NOT MATCHED THEN
  INSERT (MENU_ID, CHAVE_PAI, OPCAO, TEXTO, PROXIMA_CHAVE, ORDEM)
  VALUES (src.MENU_ID, 'root', '5', 'Enviar doc. veículo', 'ASK_DOC_VEICULO', 5);
